// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNC0MXoDFrEfSo4eJ2_8cVXbZfobqvJt0',
    appId: '1:500875522733:web:cb458d8f7757d01a52cc24',
    messagingSenderId: '500875522733',
    projectId: 'sanaa-task-manager-cw',
    authDomain: 'sanaa-task-manager-cw.firebaseapp.com',
    storageBucket: 'sanaa-task-manager-cw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChsz_MMb8V_rtjpvqNi0trXAJojaBOLU0',
    appId: '1:500875522733:android:1762c5648f13388c52cc24',
    messagingSenderId: '500875522733',
    projectId: 'sanaa-task-manager-cw',
    storageBucket: 'sanaa-task-manager-cw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPbabN2qUjDw_OgYN7MH6id4e3c7N4Ppk',
    appId: '1:500875522733:ios:d60a8dae1dcaf4a052cc24',
    messagingSenderId: '500875522733',
    projectId: 'sanaa-task-manager-cw',
    storageBucket: 'sanaa-task-manager-cw.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPbabN2qUjDw_OgYN7MH6id4e3c7N4Ppk',
    appId: '1:500875522733:ios:d60a8dae1dcaf4a052cc24',
    messagingSenderId: '500875522733',
    projectId: 'sanaa-task-manager-cw',
    storageBucket: 'sanaa-task-manager-cw.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNC0MXoDFrEfSo4eJ2_8cVXbZfobqvJt0',
    appId: '1:500875522733:web:b775b9e7dd0369d052cc24',
    messagingSenderId: '500875522733',
    projectId: 'sanaa-task-manager-cw',
    authDomain: 'sanaa-task-manager-cw.firebaseapp.com',
    storageBucket: 'sanaa-task-manager-cw.firebasestorage.app',
  );
}
